print("Smoked Turkey!")
print("Cornbread Dressing")
print("Mac and Cheese")
print("Homemade Cranberry Sauce")
print("Giblet Gravy")
print("Pecan Pie")
print("And other stuff!")
print("more stuff came at Christmas Time!")